os:
  - linux
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "6.7"
  - "6.4"
  - "6.0"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
after_success:
  - npm run coveralls
