os:
  - linux
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "6.2.1"
  - "5.5.0"
  - "5.0.0"
  - "4.5.0"
  - "4.0.0"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
